### ISSUE TITLE
wont load the module

### ISSUE THREAD

**Issue by CodingArcher** [adafruit/Adafruit_CircuitPython_SHTC3#13]
Im trying to use the SHTC3 on a pico,
when i grab the .mpy file out of the lib folder i downloaded it says that the file is corrumt. when using the .py file from this folder it doent give me any errors however i also dont get any data displayed.

**Comment by caternuson** [comment]
Make sure you are matching the bundle version with the CircuitPython version. 6.x for 6.x, 7.x for 7.x, etc.

Should work:
```python
Adafruit CircuitPython 7.0.0 on 2021-09-20; Raspberry Pi Pico with rp2040
>>> import adafruit_shtc3
>>> 
```

**Comment by caternuson** [comment]
Closing. Could not recreate issue. Either improperly downloaded, or incorrect version being used.
