### ISSUE TITLE
trying to change the i2c bus from 0 to 1

### ISSUE THREAD

**Issue by Sheng2216** [adafruit/Adafruit_CircuitPython_SHTC3#14]
Hi, I am testing the sensor on a raspberry pi, I am looking for ways to change the bus number from 0 to 1, but it seems it is defined in the library already. Is there any way to modify it?

**Comment by makermelissa** [comment]
@Sheng-IoT it looks like you pass in the I2C bus into the driver. It also sounds like you may want to use https://github.com/adafruit/Adafruit_Python_Extended_Bus. There's an example in there how to use I2C bus 1 for the Pi.
